/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GalAvatar {
        /**
          * Texte alternatif personnalisé
         */
        "alt"?: string;
        /**
          * Nom complet utilisé pour générer les initiales
         */
        "name": string;
        /**
          * Taille du composant
         */
        "size": Size;
        /**
          * URL de l’image
         */
        "src"?: string;
        /**
          * Statut affiché dans la pastille
         */
        "status": Status;
        /**
          * Variante sémantique
         */
        "variant": Variant;
    }
}
declare global {
    interface HTMLGalAvatarElement extends Components.GalAvatar, HTMLStencilElement {
    }
    var HTMLGalAvatarElement: {
        prototype: HTMLGalAvatarElement;
        new (): HTMLGalAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "gal-avatar": HTMLGalAvatarElement;
    }
}
declare namespace LocalJSX {
    interface GalAvatar {
        /**
          * Texte alternatif personnalisé
         */
        "alt"?: string;
        /**
          * Nom complet utilisé pour générer les initiales
         */
        "name"?: string;
        /**
          * Taille du composant
         */
        "size"?: Size;
        /**
          * URL de l’image
         */
        "src"?: string;
        /**
          * Statut affiché dans la pastille
         */
        "status"?: Status;
        /**
          * Variante sémantique
         */
        "variant"?: Variant;
    }
    interface IntrinsicElements {
        "gal-avatar": GalAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gal-avatar": LocalJSX.GalAvatar & JSXBase.HTMLAttributes<HTMLGalAvatarElement>;
        }
    }
}
