/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GalAvatar {
        /**
          * Custom alternative text
         */
        "alt"?: string;
        /**
          * Avatar color (semantic tokens)
         */
        "avatarColor": AvatarColor;
        /**
          * Font Awesome icon class (ex: "fas fa-user")
         */
        "icon"?: string;
        /**
          * Full name used to generate initials
         */
        "name": string;
        /**
          * Taille du composant
         */
        "size": Size;
        /**
          * URL de l'image
         */
        "src"?: string;
        /**
          * Status displayed inside the badge
         */
        "status": Status;
        /**
          * Variant: primary or secondary
         */
        "variant": AvatarVariant;
    }
    interface GalBadge {
        /**
          * Color variant
         */
        "color": BadgeColor;
        /**
          * Icon class (Font Awesome)
         */
        "icon"?: string;
        /**
          * Mode: number or icon
         */
        "mode": BadgeMode;
        /**
          * Number to display
         */
        "number"?: number;
        /**
          * Size of the badge
         */
        "size": BadgeSize;
        /**
          * Variant: primary (filled) or secondary (bordered)
         */
        "variant": BadgeVariant;
    }
    interface GalBullet {
        /**
          * Color theme based on semantic tokens
         */
        "color": BulletColor;
        /**
          * Size of the bullet: xsmall (6px), small (10px), medium (18px)
         */
        "size": BulletSize;
        /**
          * Variant: filled (primary) or light (secondary)
         */
        "variant": BulletVariant;
    }
    interface GalButton {
        /**
          * Color theme of the button
         */
        "colorVariant": ButtonColorVariant;
        /**
          * If true, button is disabled
         */
        "disabled": boolean;
        /**
          * If true, button takes full width
         */
        "fullWidth": boolean;
        /**
          * If true, only shows icon without text
         */
        "iconOnly": boolean;
        /**
          * If true, shows loading spinner
         */
        "loading": boolean;
        /**
          * Size of the button
         */
        "size": ButtonSize;
        /**
          * HTML button type
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Style variant of the button
         */
        "variant": ButtonVariant;
    }
    interface GalCheckbox {
        /**
          * Whether the checkbox is checked
         */
        "checked": boolean;
        /**
          * Disable interactions
         */
        "disabled": boolean;
        /**
          * Indeterminate visual state (minus)
         */
        "indeterminate": boolean;
        /**
          * Optional label text (fallback if no slot)
         */
        "label"?: string;
        /**
          * Native input name
         */
        "name"?: string;
        /**
          * Native input value
         */
        "value"?: string;
    }
    interface GalLabel {
        /**
          * Palette aligned with the React implementation
         */
        "color": LabelColor;
        /**
          * Optional Font Awesome class for the icon
         */
        "icon"?: string;
        /**
          * Taille du label
         */
        "size": LabelSize;
        /**
          * Text rendered inside the label (fallback when no slot)
         */
        "text": string;
    }
}
export interface GalCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGalCheckboxElement;
}
declare global {
    interface HTMLGalAvatarElement extends Components.GalAvatar, HTMLStencilElement {
    }
    var HTMLGalAvatarElement: {
        prototype: HTMLGalAvatarElement;
        new (): HTMLGalAvatarElement;
    };
    interface HTMLGalBadgeElement extends Components.GalBadge, HTMLStencilElement {
    }
    var HTMLGalBadgeElement: {
        prototype: HTMLGalBadgeElement;
        new (): HTMLGalBadgeElement;
    };
    interface HTMLGalBulletElement extends Components.GalBullet, HTMLStencilElement {
    }
    var HTMLGalBulletElement: {
        prototype: HTMLGalBulletElement;
        new (): HTMLGalBulletElement;
    };
    interface HTMLGalButtonElement extends Components.GalButton, HTMLStencilElement {
    }
    var HTMLGalButtonElement: {
        prototype: HTMLGalButtonElement;
        new (): HTMLGalButtonElement;
    };
    interface HTMLGalCheckboxElement extends Components.GalCheckbox, HTMLStencilElement {
    }
    var HTMLGalCheckboxElement: {
        prototype: HTMLGalCheckboxElement;
        new (): HTMLGalCheckboxElement;
    };
    interface HTMLGalLabelElement extends Components.GalLabel, HTMLStencilElement {
    }
    var HTMLGalLabelElement: {
        prototype: HTMLGalLabelElement;
        new (): HTMLGalLabelElement;
    };
    interface HTMLElementTagNameMap {
        "gal-avatar": HTMLGalAvatarElement;
        "gal-badge": HTMLGalBadgeElement;
        "gal-bullet": HTMLGalBulletElement;
        "gal-button": HTMLGalButtonElement;
        "gal-checkbox": HTMLGalCheckboxElement;
        "gal-label": HTMLGalLabelElement;
    }
}
declare namespace LocalJSX {
    interface GalAvatar {
        /**
          * Custom alternative text
         */
        "alt"?: string;
        /**
          * Avatar color (semantic tokens)
         */
        "avatarColor"?: AvatarColor;
        /**
          * Font Awesome icon class (ex: "fas fa-user")
         */
        "icon"?: string;
        /**
          * Full name used to generate initials
         */
        "name"?: string;
        /**
          * Taille du composant
         */
        "size"?: Size;
        /**
          * URL de l'image
         */
        "src"?: string;
        /**
          * Status displayed inside the badge
         */
        "status"?: Status;
        /**
          * Variant: primary or secondary
         */
        "variant"?: AvatarVariant;
    }
    interface GalBadge {
        /**
          * Color variant
         */
        "color"?: BadgeColor;
        /**
          * Icon class (Font Awesome)
         */
        "icon"?: string;
        /**
          * Mode: number or icon
         */
        "mode"?: BadgeMode;
        /**
          * Number to display
         */
        "number"?: number;
        /**
          * Size of the badge
         */
        "size"?: BadgeSize;
        /**
          * Variant: primary (filled) or secondary (bordered)
         */
        "variant"?: BadgeVariant;
    }
    interface GalBullet {
        /**
          * Color theme based on semantic tokens
         */
        "color"?: BulletColor;
        /**
          * Size of the bullet: xsmall (6px), small (10px), medium (18px)
         */
        "size"?: BulletSize;
        /**
          * Variant: filled (primary) or light (secondary)
         */
        "variant"?: BulletVariant;
    }
    interface GalButton {
        /**
          * Color theme of the button
         */
        "colorVariant"?: ButtonColorVariant;
        /**
          * If true, button is disabled
         */
        "disabled"?: boolean;
        /**
          * If true, button takes full width
         */
        "fullWidth"?: boolean;
        /**
          * If true, only shows icon without text
         */
        "iconOnly"?: boolean;
        /**
          * If true, shows loading spinner
         */
        "loading"?: boolean;
        /**
          * Size of the button
         */
        "size"?: ButtonSize;
        /**
          * HTML button type
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Style variant of the button
         */
        "variant"?: ButtonVariant;
    }
    interface GalCheckbox {
        /**
          * Whether the checkbox is checked
         */
        "checked"?: boolean;
        /**
          * Disable interactions
         */
        "disabled"?: boolean;
        /**
          * Indeterminate visual state (minus)
         */
        "indeterminate"?: boolean;
        /**
          * Optional label text (fallback if no slot)
         */
        "label"?: string;
        /**
          * Native input name
         */
        "name"?: string;
        "onGalBlur"?: (event: GalCheckboxCustomEvent<FocusEvent>) => void;
        "onGalChange"?: (event: GalCheckboxCustomEvent<boolean>) => void;
        "onGalCheckedChange"?: (event: GalCheckboxCustomEvent<boolean>) => void;
        "onGalFocus"?: (event: GalCheckboxCustomEvent<FocusEvent>) => void;
        /**
          * Native input value
         */
        "value"?: string;
    }
    interface GalLabel {
        /**
          * Palette aligned with the React implementation
         */
        "color"?: LabelColor;
        /**
          * Optional Font Awesome class for the icon
         */
        "icon"?: string;
        /**
          * Taille du label
         */
        "size"?: LabelSize;
        /**
          * Text rendered inside the label (fallback when no slot)
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "gal-avatar": GalAvatar;
        "gal-badge": GalBadge;
        "gal-bullet": GalBullet;
        "gal-button": GalButton;
        "gal-checkbox": GalCheckbox;
        "gal-label": GalLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gal-avatar": LocalJSX.GalAvatar & JSXBase.HTMLAttributes<HTMLGalAvatarElement>;
            "gal-badge": LocalJSX.GalBadge & JSXBase.HTMLAttributes<HTMLGalBadgeElement>;
            "gal-bullet": LocalJSX.GalBullet & JSXBase.HTMLAttributes<HTMLGalBulletElement>;
            "gal-button": LocalJSX.GalButton & JSXBase.HTMLAttributes<HTMLGalButtonElement>;
            "gal-checkbox": LocalJSX.GalCheckbox & JSXBase.HTMLAttributes<HTMLGalCheckboxElement>;
            "gal-label": LocalJSX.GalLabel & JSXBase.HTMLAttributes<HTMLGalLabelElement>;
        }
    }
}
